import { createContext, useContext, useState, useCallback } from "react";

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
];

const translations = {
  en: {
    profile: "Profile",
    overview: "Overview",
    accountSettings: "Account Settings",
    preferences: "Preferences",
    watchlistBids: "Watchlist & Bids",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    bio: "Bio",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    save: "Save Changes",
    clear: "Clear",
    updateProfile: "Update Profile",
    theme: "Theme",
    language: "Language",
    selectTheme: "Select Theme",
    selectLanguage: "Select Language",
    memberSince: "Member Since",
    verifiedMember: "Verified Member",
    totalBids: "Total Bids",
    watchlistItems: "Watchlist Items",
    activeAuctions: "Active Auctions",
    goToChat: "Go to Chat",
    viewMarketplace: "View Marketplace",
    createAuction: "Create Auction",
    myDashboard: "My Dashboard",
    manageProfile: "Manage your profile, preferences, and saved items.",
    myWatchlist: "My Saved Auctions",
    activeBids: "Active Bids",
    emptyWatchlist: "Your watchlist is empty",
    emptyBids: "You haven't bid on any active items.",
    exploreCta: "Explore auctions and click the heart icon to save them here.",
    bidsCta: "Explore the marketplace to find items to bid on.",
    profileUpdated: "Profile updated successfully",
    passwordChanged: "Password Changed Successfully",
    appearanceSettings: "Appearance & Language",
    chooseTheme: "Choose how Auction World looks for you",
    chooseLanguage: "Choose your preferred language",
    saving: "Saving...",
    home: "Home",
    about: "About",
    contact: "Contact Support",
    legal: "Legal",
    marketplace: "Marketplace",
    dashboard: "Dashboard",
    myInventory: "My Inventory",
    history: "History",
    messages: "Messages",
    logIn: "Log in",
    signUp: "Sign up",
    signOut: "Sign out",
    notifications: "Notifications",
    markAllRead: "Mark all Read",
    viewCompleteHistory: "View Complete History",
  },
  hi: {
    profile: "प्रोफ़ाइल",
    overview: "अवलोकन",
    accountSettings: "खाता सेटिंग्स",
    preferences: "प्राथमिकताएं",
    watchlistBids: "वॉचलिस्ट और बोलियां",
    personalInfo: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    email: "ईमेल पता",
    phone: "फ़ोन नंबर",
    bio: "परिचय",
    changePassword: "पासवर्ड बदलें",
    currentPassword: "वर्तमान पासवर्ड",
    newPassword: "नया पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    save: "परिवर्तन सहेजें",
    clear: "साफ़ करें",
    updateProfile: "प्रोफ़ाइल अपडेट करें",
    theme: "थीम",
    language: "भाषा",
    selectTheme: "थीम चुनें",
    selectLanguage: "भाषा चुनें",
    memberSince: "सदस्य बने",
    verifiedMember: "सत्यापित सदस्य",
    totalBids: "कुल बोलियां",
    watchlistItems: "वॉचलिस्ट आइटम",
    activeAuctions: "सक्रिय नीलामी",
    goToChat: "चैट पर जाएं",
    viewMarketplace: "बाज़ार देखें",
    createAuction: "नीलामी बनाएं",
    myDashboard: "मेरा डैशबोर्ड",
    manageProfile: "अपनी प्रोफ़ाइल, प्राथमिकताएं और सहेजे गए आइटम प्रबंधित करें।",
    myWatchlist: "मेरी सहेजी गई नीलामी",
    activeBids: "सक्रिय बोलियां",
    emptyWatchlist: "आपकी वॉचलिस्ट खाली है",
    emptyBids: "आपने किसी सक्रिय आइटम पर बोली नहीं लगाई है।",
    exploreCta: "नीलामी खोजें और दिल आइकन पर क्लिक करें।",
    bidsCta: "बोली लगाने के लिए बाज़ार खोजें।",
    profileUpdated: "प्रोफ़ाइल सफलतापूर्वक अपडेट किया गया",
    passwordChanged: "पासवर्ड सफलतापूर्वक बदला गया",
    appearanceSettings: "दिखावट और भाषा",
    chooseTheme: "चुनें कि नीलामी वर्ल्ड आपके लिए कैसा दिखे",
    chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
    saving: "सहेज रहा है...",
    home: "मुख्य पृष्ठ",
    about: "हमारे बारे में",
    contact: "संपर्क करें",
    legal: "कानूनी",
    marketplace: "बाज़ार",
    dashboard: "डैशबोर्ड",
    myInventory: "मेरी इन्वेंटरी",
    history: "इतिहास",
    messages: "संदेश",
    logIn: "लॉग इन",
    signUp: "साइन अप",
    signOut: "साइन आउट",
    notifications: "सूचनाएं",
    markAllRead: "सभी पढ़ी गई चिह्नित करें",
    viewCompleteHistory: "पूरा इतिहास देखें",
  },
  es: {
    profile: "Perfil",
    overview: "Resumen",
    accountSettings: "Configuración de Cuenta",
    preferences: "Preferencias",
    watchlistBids: "Lista y Pujas",
    personalInfo: "Información Personal",
    fullName: "Nombre Completo",
    email: "Correo Electrónico",
    phone: "Teléfono",
    bio: "Biografía",
    changePassword: "Cambiar Contraseña",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    save: "Guardar Cambios",
    clear: "Limpiar",
    updateProfile: "Actualizar Perfil",
    theme: "Tema",
    language: "Idioma",
    selectTheme: "Seleccionar Tema",
    selectLanguage: "Seleccionar Idioma",
    memberSince: "Miembro Desde",
    verifiedMember: "Miembro Verificado",
    totalBids: "Total de Pujas",
    watchlistItems: "Lista de Seguimiento",
    activeAuctions: "Subastas Activas",
    goToChat: "Ir al Chat",
    viewMarketplace: "Ver Mercado",
    createAuction: "Crear Subasta",
    myDashboard: "Mi Panel",
    manageProfile: "Administra tu perfil, preferencias y artículos guardados.",
    myWatchlist: "Mis Subastas Guardadas",
    activeBids: "Pujas Activas",
    emptyWatchlist: "Tu lista está vacía",
    emptyBids: "No has pujado en ningún artículo activo.",
    exploreCta: "Explora subastas y haz clic en el corazón para guardarlas.",
    bidsCta: "Explora el mercado para encontrar artículos.",
    profileUpdated: "Perfil actualizado correctamente",
    passwordChanged: "Contraseña cambiada correctamente",
    appearanceSettings: "Apariencia e Idioma",
    chooseTheme: "Elige cómo se ve Auction World para ti",
    chooseLanguage: "Elige tu idioma preferido",
    saving: "Guardando...",
    home: "Inicio",
    about: "Acerca de",
    contact: "Contacto",
    legal: "Legal",
    marketplace: "Mercado",
    dashboard: "Panel",
    myInventory: "Mi Inventario",
    history: "Historial",
    messages: "Mensajes",
    logIn: "Iniciar sesión",
    signUp: "Regístrate",
    signOut: "Cerrar sesión",
    notifications: "Notificaciones",
    markAllRead: "Marcar todo como leído",
    viewCompleteHistory: "Ver historial completo",
  },
  fr: {
    profile: "Profil",
    overview: "Aperçu",
    accountSettings: "Paramètres du Compte",
    preferences: "Préférences",
    watchlistBids: "Liste & Enchères",
    personalInfo: "Informations Personnelles",
    fullName: "Nom Complet",
    email: "Adresse E-mail",
    phone: "Téléphone",
    bio: "Biographie",
    changePassword: "Changer le Mot de Passe",
    currentPassword: "Mot de Passe Actuel",
    newPassword: "Nouveau Mot de Passe",
    confirmPassword: "Confirmer le Mot de Passe",
    save: "Enregistrer",
    clear: "Effacer",
    updateProfile: "Mettre à Jour le Profil",
    theme: "Thème",
    language: "Langue",
    selectTheme: "Sélectionner le Thème",
    selectLanguage: "Sélectionner la Langue",
    memberSince: "Membre Depuis",
    verifiedMember: "Membre Vérifié",
    totalBids: "Total des Enchères",
    watchlistItems: "Liste de Suivi",
    activeAuctions: "Enchères Actives",
    goToChat: "Aller au Chat",
    viewMarketplace: "Voir le Marché",
    createAuction: "Créer une Enchère",
    myDashboard: "Mon Tableau de Bord",
    manageProfile: "Gérez votre profil, préférences et articles sauvegardés.",
    myWatchlist: "Mes Enchères Sauvegardées",
    activeBids: "Enchères Actives",
    emptyWatchlist: "Votre liste est vide",
    emptyBids: "Vous n'avez misé sur aucun article actif.",
    exploreCta: "Explorez les enchères et cliquez sur le cœur pour les sauvegarder.",
    bidsCta: "Explorez le marché pour trouver des articles.",
    profileUpdated: "Profil mis à jour avec succès",
    passwordChanged: "Mot de passe changé avec succès",
    appearanceSettings: "Apparence et Langue",
    chooseTheme: "Choisissez l'apparence d'Auction World",
    chooseLanguage: "Choisissez votre langue préférée",
    saving: "Enregistrement...",
    home: "Accueil",
    about: "À propos",
    contact: "Contact",
    legal: "Légal",
    marketplace: "Marché",
    dashboard: "Tableau de bord",
    myInventory: "Mon Inventaire",
    history: "Historique",
    messages: "Messages",
    logIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Se déconnecter",
    notifications: "Notifications",
    markAllRead: "Tout marquer comme lu",
    viewCompleteHistory: "Voir l'historique complet",
  },
  de: {
    profile: "Profil",
    overview: "Übersicht",
    accountSettings: "Kontoeinstellungen",
    preferences: "Einstellungen",
    watchlistBids: "Merkliste & Gebote",
    personalInfo: "Persönliche Informationen",
    fullName: "Vollständiger Name",
    email: "E-Mail-Adresse",
    phone: "Telefonnummer",
    bio: "Biografie",
    changePassword: "Passwort Ändern",
    currentPassword: "Aktuelles Passwort",
    newPassword: "Neues Passwort",
    confirmPassword: "Passwort Bestätigen",
    save: "Änderungen Speichern",
    clear: "Löschen",
    updateProfile: "Profil Aktualisieren",
    theme: "Design",
    language: "Sprache",
    selectTheme: "Design Wählen",
    selectLanguage: "Sprache Wählen",
    memberSince: "Mitglied Seit",
    verifiedMember: "Verifiziertes Mitglied",
    totalBids: "Gebote Gesamt",
    watchlistItems: "Merkliste",
    activeAuctions: "Aktive Auktionen",
    goToChat: "Zum Chat",
    viewMarketplace: "Marktplatz Ansehen",
    createAuction: "Auktion Erstellen",
    myDashboard: "Mein Dashboard",
    manageProfile: "Verwalten Sie Ihr Profil, Ihre Einstellungen und gespeicherte Artikel.",
    myWatchlist: "Meine Gespeicherten Auktionen",
    activeBids: "Aktive Gebote",
    emptyWatchlist: "Ihre Merkliste ist leer",
    emptyBids: "Sie haben noch keine Gebote abgegeben.",
    exploreCta: "Erkunden Sie Auktionen und klicken Sie auf das Herz-Symbol.",
    bidsCta: "Erkunden Sie den Marktplatz.",
    profileUpdated: "Profil erfolgreich aktualisiert",
    passwordChanged: "Passwort erfolgreich geändert",
    appearanceSettings: "Aussehen & Sprache",
    chooseTheme: "Wählen Sie das Aussehen von Auction World",
    chooseLanguage: "Wählen Sie Ihre bevorzugte Sprache",
    saving: "Speichern...",
    home: "Startseite",
    about: "Über uns",
    contact: "Kontakt",
    legal: "Rechtliches",
    marketplace: "Marktplatz",
    dashboard: "Dashboard",
    myInventory: "Mein Inventar",
    history: "Verlauf",
    messages: "Nachrichten",
    logIn: "Anmelden",
    signUp: "Registrieren",
    signOut: "Abmelden",
    notifications: "Benachrichtigungen",
    markAllRead: "Alle als gelesen markieren",
    viewCompleteHistory: "Vollständigen Verlauf anzeigen",
  },
  ja: {
    profile: "プロフィール",
    overview: "概要",
    accountSettings: "アカウント設定",
    preferences: "環境設定",
    watchlistBids: "ウォッチリストと入札",
    personalInfo: "個人情報",
    fullName: "氏名",
    email: "メールアドレス",
    phone: "電話番号",
    bio: "自己紹介",
    changePassword: "パスワード変更",
    currentPassword: "現在のパスワード",
    newPassword: "新しいパスワード",
    confirmPassword: "パスワード確認",
    save: "変更を保存",
    clear: "クリア",
    updateProfile: "プロフィール更新",
    theme: "テーマ",
    language: "言語",
    selectTheme: "テーマを選択",
    selectLanguage: "言語を選択",
    memberSince: "登録日",
    verifiedMember: "認証済み会員",
    totalBids: "合計入札数",
    watchlistItems: "ウォッチリスト",
    activeAuctions: "アクティブなオークション",
    goToChat: "チャットへ",
    viewMarketplace: "マーケットプレイス",
    createAuction: "オークション作成",
    myDashboard: "マイダッシュボード",
    manageProfile: "プロフィール、設定、保存済みアイテムを管理します。",
    myWatchlist: "保存済みオークション",
    activeBids: "アクティブな入札",
    emptyWatchlist: "ウォッチリストは空です",
    emptyBids: "まだ入札していません。",
    exploreCta: "オークションを探して、ハートアイコンをクリックして保存してください。",
    bidsCta: "マーケットプレイスで入札するアイテムを見つけましょう。",
    profileUpdated: "プロフィールが正常に更新されました",
    passwordChanged: "パスワードが正常に変更されました",
    appearanceSettings: "外観と言語",
    chooseTheme: "Auction Worldの外観を選択",
    chooseLanguage: "好みの言語を選択",
    saving: "保存中...",
    home: "ホーム",
    about: "約",
    contact: "接触",
    legal: "法的",
    marketplace: "市場",
    dashboard: "ダッシュボード",
    myInventory: "マイインベントリ",
    history: "歴史",
    messages: "メッセージ",
    logIn: "ログイン",
    signUp: "サインアップ",
    signOut: "サインアウト",
    notifications: "通知",
    markAllRead: "すべて既読にする",
    viewCompleteHistory: "完全な履歴を見る",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("aw-lang") || "en";
  });

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem("aw-lang", lang);
  }, []);

  const t = useCallback(
    (key) => {
      return translations[language]?.[key] || translations.en[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
